services:
  _defaults:
    public: true

  Sendy\PrestaShop\Grid\Carrier\CarrierGridDataFactory:
    class: 'Sendy\PrestaShop\Grid\Carrier\CarrierGridDataFactory'
  Sendy\PrestaShop\Grid\Carrier\CarrierGridDefinitionFactory:
    class: 'Sendy\PrestaShop\Grid\Carrier\CarrierGridDefinitionFactory'
    arguments:
      - '@prestashop.hook.dispatcher'
      - '@translator'
      - '@Sendy\PrestaShop\Form\Carrier\CarrierChoiceProvider'
  Sendy\PrestaShop\Grid\Carrier\CarrierGridFactory:
    class: 'Sendy\PrestaShop\Grid\Carrier\CarrierGridFactory'
    arguments:
      - '@Sendy\PrestaShop\Grid\Carrier\CarrierGridDefinitionFactory'
      - '@Sendy\PrestaShop\Grid\Carrier\CarrierGridDataFactory'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

