name: sendy-prestashop-1.7
services:
  mysql:
    container_name: sendy-prestashop-1.7-mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
  prestashop:
    container_name: sendy-prestashop-1.7-prestashop
    image: prestashop/prestashop:1.7.8
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8017:80
    volumes:
      - ./prestashop-1.7:/var/www/html
      - ./:/var/www/html/modules/sendy
    environment:
      DB_SERVER: sendy-prestashop-1.7-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8017
      PS_FOLDER_ADMIN: admin7639
      PS_DEV_MODE: 1
      PS_LANGUAGE: nl
    networks:
      - prestashop_network
networks:
  prestashop_network:
volumes:
  db_data:
    driver: local
