name: sendy-prestashop-9
services:
  mysql:
    container_name: sendy-prestashop-9-mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  prestashop:
    container_name: sendy-prestashop-9-prestashop
    image: prestashop/prestashop:9.0.0-1.0-classic
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8090:80
    volumes:
      - ./prestashop-9:/var/www/html
      - ./:/var/www/html/modules/sendy
    environment:
      DB_SERVER: sendy-prestashop-9-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8090
      PS_FOLDER_ADMIN: admin7639
      PS_DEV_MODE: 1
      PS_LANGUAGE: en
      PS_COUNTRY: NL
    networks:
      - prestashop_network
networks:
  prestashop_network:
