sendynl_settings:
  path: /sendynl/settings
  methods: [GET, POST]
  defaults:
    _controller: 'Sendy\PrestaShop\Controller\Admin\SettingsController::index'
    # Needed to work with tab system
    _legacy_controller: 'AdminSendynlSettings'
    _legacy_link: 'AdminSendynlSettings'

sendynl_login:
  path: /sendynl/login
  methods: [POST]
  defaults:
    _controller: 'Sendy\PrestaShop\Controller\Admin\AuthController::login'
sendynl_login_callback:
  path: /sendynl/login/callback
  methods: [GET]
  defaults:
    _controller: 'Sendy\PrestaShop\Controller\Admin\AuthController::callback'
    _anonymous_controller: true
    _legacy_controller_anonymous: true
sendynl_logout:
  path: /sendynl/logout
  methods: [POST]
  defaults:
    _controller: 'Sendy\PrestaShop\Controller\Admin\AuthController::logout'

sendynl_carriers_store:
  path: /sendynl/carriers
  methods: [POST]
  defaults:
    _controller: 'Sendy\PrestaShop\Controller\Admin\CarrierController::store'

sendynl_carriers_update:
  path: /sendynl/carriers/{carrierId}/parcel-shop-carrier
  methods: [POST]
  defaults:
      _controller: 'Sendy\PrestaShop\Controller\Admin\CarrierController::updateParcelShopCarrier'

sendynl_orders_create_shipment:
  path: /sendynl/orders/create-shipment
  methods: [POST]
  defaults:
    _controller: 'Sendy\PrestaShop\Controller\Admin\Orders\CreateShipmentController::__invoke'
sendynl_orders_print_label:
  path: /sendynl/orders/print-label
  methods: [GET]
  defaults:
    _controller: 'Sendy\PrestaShop\Controller\Admin\Orders\PrintLabelController::__invoke'
sendynl_orders_toggle_track_and_trace_column:
  path: /sendynl/orders/toggle-track-and-trace-column
  methods: [POST]
  defaults:
    _controller: 'Sendy\PrestaShop\Controller\Admin\Orders\ColumnsController::toggleTrackAndTraceColumn'
