services:
  _defaults:
    public: true

  # Actions
  Sendy\PrestaShop\Action\CreateShipmentFromOrder:
    class: 'Sendy\PrestaShop\Action\CreateShipmentFromOrder'
    arguments:
      - '@Sendy\PrestaShop\Factory\ApiConnectionFactory'
      - '@Sendy\PrestaShop\Repository\ShopConfigurationRepository'
  Sendy\PrestaShop\Action\HandleShipmentWebhook:
    class: 'Sendy\PrestaShop\Action\HandleShipmentWebhook'
    arguments:
      - '@Sendy\PrestaShop\Repository\ShipmentRepository'
      - '@Sendy\PrestaShop\Repository\PackageRepository'
      - '@Sendy\PrestaShop\Repository\ShopConfigurationRepository'
      - '@Sendy\PrestaShop\Factory\ApiConnectionFactory'
      - '@prestashop.adapter.shop.context'
  Sendy\PrestaShop\Action\InstallWebhook:
    class: 'Sendy\PrestaShop\Action\InstallWebhook'
    arguments:
      - '@Sendy\PrestaShop\Repository\ConfigurationRepository'
      - '@Sendy\PrestaShop\Repository\ShopConfigurationRepository'
      - '@router'
      - '@Sendy\PrestaShop\Factory\ApiConnectionFactory'
  Sendy\PrestaShop\Action\SynchronizeWebhook:
    class: 'Sendy\PrestaShop\Action\SynchronizeWebhook'
    arguments:
      - '@Sendy\PrestaShop\Action\InstallWebhook'
      - '@Sendy\PrestaShop\Action\UninstallWebhook'
      - '@Sendy\PrestaShop\Repository\ShopConfigurationRepository'
  Sendy\PrestaShop\Action\UninstallWebhook:
    class: 'Sendy\PrestaShop\Action\UninstallWebhook'
    arguments:
      - '@Sendy\PrestaShop\Repository\ConfigurationRepository'
      - '@Sendy\PrestaShop\Factory\ApiConnectionFactory'

  # Controllers
  Sendy\PrestaShop\Controller\Admin\AuthController:
    class: 'Sendy\PrestaShop\Controller\Admin\AuthController'
    arguments:
      - '@Sendy\PrestaShop\Repository\ConfigurationRepository'
      - '@Sendy\PrestaShop\Factory\ApiConnectionFactory'
      - '@router'
      - '@Sendy\PrestaShop\Action\InstallWebhook'
    parent: 'PrestaShopBundle\Controller\Admin\FrameworkBundleAdminController'
    public: true
  Sendy\PrestaShop\Controller\Admin\SettingsController:
    class: 'Sendy\PrestaShop\Controller\Admin\SettingsController'
    arguments:
      - '@Sendy\PrestaShop\Repository\ConfigurationRepository'
      - '@Sendy\PrestaShop\Repository\ShopConfigurationRepository'
      - '@Sendy\PrestaShop\Form\Settings\SettingsFormHandler'
      - '@Sendy\PrestaShop\Action\SynchronizeWebhook'
      - '@Sendy\PrestaShop\Grid\Carrier\CarrierGridFactory'
  Sendy\PrestaShop\Controller\Admin\Orders\CreateShipmentController:
    class: 'Sendy\PrestaShop\Controller\Admin\Orders\CreateShipmentController'
    arguments:
      - '@Sendy\PrestaShop\Action\CreateShipmentFromOrder'
  Sendy\PrestaShop\Controller\Admin\Orders\PrintLabelController:
    class: 'Sendy\PrestaShop\Controller\Admin\Orders\PrintLabelController'
    arguments:
      - '@Sendy\PrestaShop\Factory\ApiConnectionFactory'
      - '@Sendy\PrestaShop\Repository\ShipmentRepository'
  Sendy\PrestaShop\Controller\Admin\Orders\ColumnsController:
    class: 'Sendy\PrestaShop\Controller\Admin\Orders\ColumnsController'
    arguments:
      - '@Sendy\PrestaShop\Repository\ConfigurationRepository'
  Sendy\PrestaShop\Controller\Admin\WebhookController:
    class: 'Sendy\PrestaShop\Controller\Admin\WebhookController'
    arguments:
      - '@Sendy\PrestaShop\Repository\ShipmentRepository'
      - '@Sendy\PrestaShop\Action\HandleShipmentWebhook'
      - '@Sendy\PrestaShop\Repository\ConfigurationRepository'

  # Factories
  Sendy\PrestaShop\Factory\ApiConnectionFactory:
    class: 'Sendy\PrestaShop\Factory\ApiConnectionFactory'
    arguments:
      - '@Sendy\PrestaShop\Repository\ConfigurationRepository'
      - '@router'

  # Forms
  Sendy\PrestaShop\Form\CreateShipment\CreateShipmentForm:
    class: 'Sendy\PrestaShop\Form\CreateShipment\CreateShipmentForm'
    arguments:
      - '@translator'
      - '@Sendy\PrestaShop\Factory\ApiConnectionFactory'
    tags:
      - { name: form.type }
  Sendy\PrestaShop\Form\CreateShipment\CreateShipmentFormHandler:
    class: 'Sendy\PrestaShop\Form\CreateShipment\CreateShipmentFormHandler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@Sendy\PrestaShop\Form\CreateShipment\CreateShipmentFormDataProvider'
  Sendy\PrestaShop\Form\CreateShipment\CreateShipmentFormDataProvider:
    class: 'Sendy\PrestaShop\Form\CreateShipment\CreateShipmentFormDataProvider'
    arguments:
      - '@Sendy\PrestaShop\Repository\ShopConfigurationRepository'
  Sendy\PrestaShop\Form\Settings\AuthenticateForm:
    class: Sendy\PrestaShop\Form\Settings\AuthenticateForm
    arguments:
      - '@translator'
      - "@=service('prestashop.adapter.legacy.context').getLanguages()"
      - '@router'
      - '@Sendy\PrestaShop\Factory\ApiConnectionFactory'
    tags:
      - { name: form.type }
  Sendy\PrestaShop\Form\Settings\SettingsDataManager:
    class: 'Sendy\PrestaShop\Form\Settings\SettingsDataManager'
    arguments:
      - '@Sendy\PrestaShop\Repository\ShopConfigurationRepository'
  Sendy\PrestaShop\Form\Settings\SettingsForm:
    class: 'Sendy\PrestaShop\Form\Settings\SettingsForm'
    arguments:
      - '@translator'
      - '@prestashop.core.form.choice_provider.order_state_by_id'
      - '@Sendy\PrestaShop\Form\Settings\ShopChoiceProvider'
    tags:
      - { name: form.type }
  Sendy\PrestaShop\Form\Settings\SettingsFormHandler:
    class: 'Sendy\PrestaShop\Form\Settings\SettingsFormHandler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@Sendy\PrestaShop\Form\Settings\SettingsDataManager'
  Sendy\PrestaShop\Form\Settings\ShopChoiceProvider:
    class: 'Sendy\PrestaShop\Form\Settings\ShopChoiceProvider'
    arguments:
      - '@Sendy\PrestaShop\Factory\ApiConnectionFactory'

  # Grid
  Sendy\PrestaShop\Grid\Carrier\CarrierGridDataFactory:
    class: 'Sendy\PrestaShop\Grid\Carrier\CarrierGridDataFactory'
    public: true
  Sendy\PrestaShop\Grid\Carrier\CarrierGridDefinitionFactory:
    class: 'Sendy\PrestaShop\Grid\Carrier\CarrierGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true
  Sendy\PrestaShop\Grid\Carrier\CarrierGridFactory:
    class: 'Sendy\PrestaShop\Grid\Carrier\CarrierGridFactory'
    public: true
    arguments:
      - '@Sendy\PrestaShop\Grid\Carrier\CarrierGridDefinitionFactory'
      - '@Sendy\PrestaShop\Grid\Carrier\CarrierGridDataFactory'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  # Hooks
  Sendy\PrestaShop\Hook\Admin\ActionAdminControllerSetMedia:
    class: 'Sendy\PrestaShop\Hook\Admin\ActionAdminControllerSetMedia'
    arguments:
      - '@router'
  Sendy\PrestaShop\Hook\Admin\ActionAfterCreateCarrierFormHandler:
    class: 'Sendy\PrestaShop\Hook\Admin\ActionAfterCreateCarrierFormHandler'
    arguments:
      - '@Sendy\PrestaShop\Repository\CarrierConfigRepository'
  Sendy\PrestaShop\Hook\Admin\ActionAfterUpdateCarrierFormHandler:
    class: 'Sendy\PrestaShop\Hook\Admin\ActionAfterCreateCarrierFormHandler'
    arguments:
      - '@Sendy\PrestaShop\Repository\CarrierConfigRepository'
  Sendy\PrestaShop\Hook\Admin\ActionCarrierFormBuilderModifier:
    class: 'Sendy\PrestaShop\Hook\Admin\ActionCarrierFormBuilderModifier'
  Sendy\PrestaShop\Hook\Admin\ActionCarrierFormDataProviderData:
    class: 'Sendy\PrestaShop\Hook\Admin\ActionCarrierFormDataProviderData'
    arguments:
      - '@Sendy\PrestaShop\Repository\CarrierConfigRepository'
  Sendy\PrestaShop\Hook\Admin\ActionOrderGridDefinitionModifier:
    class: 'Sendy\PrestaShop\Hook\Admin\ActionOrderGridDefinitionModifier'
    arguments:
      - '@translator'
      - '@Sendy\PrestaShop\Repository\ConfigurationRepository'
  Sendy\PrestaShop\Hook\Admin\DisplayAdminOrderSide:
    class: 'Sendy\PrestaShop\Hook\Admin\DisplayAdminOrderSide'
    arguments:
      - '@twig'
      - '@Sendy\PrestaShop\Form\CreateShipment\CreateShipmentFormHandler'
      - '@Sendy\PrestaShop\Repository\ShipmentRepository'
      - '@Sendy\PrestaShop\Repository\PackageRepository'
      - '@Sendy\PrestaShop\Repository\ShopConfigurationRepository'
  Sendy\PrestaShop\Hook\Admin\DisplayAdminEndContent:
    class: 'Sendy\PrestaShop\Hook\Admin\DisplayAdminEndContent'
    arguments:
      - '@twig'
      - '@Sendy\PrestaShop\Form\CreateShipment\CreateShipmentFormHandler'

  # Repositories
  Sendy\PrestaShop\Repository\CarrierConfigRepository:
    parent: 'Sendy\PrestaShop\Repository\AbstractEntityRepository'
    public: true
  Sendy\PrestaShop\Repository\AbstractEntityRepository:
    class: 'Sendy\PrestaShop\Repository\AbstractEntityRepository'
    arguments:
      - '@doctrine.orm.entity_manager'
  Sendy\PrestaShop\Repository\ShipmentRepository:
    parent: 'Sendy\PrestaShop\Repository\AbstractEntityRepository'
    public: true
  Sendy\PrestaShop\Repository\PackageRepository:
    parent: 'Sendy\PrestaShop\Repository\AbstractEntityRepository'
    public: true
  Sendy\PrestaShop\Repository\ConfigurationRepository:
    class: 'Sendy\PrestaShop\Repository\ConfigurationRepository'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
  Sendy\PrestaShop\Repository\ShopConfigurationRepository:
    class: 'Sendy\PrestaShop\Repository\ShopConfigurationRepository'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.shop.context'
