services:
  _defaults:
    public: true

  Sendy\PrestaShop\Actions\CreateShipmentFromOrder:
    class: 'Sendy\PrestaShop\Actions\CreateShipmentFromOrder'
    arguments:
      - '@Sendy\PrestaShop\Factories\ApiConnectionFactory'
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'

  Sendy\PrestaShop\Controllers\Admin\AuthController:
    class: 'Sendy\PrestaShop\Controllers\Admin\AuthController'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
      - '@Sendy\PrestaShop\Factories\ApiConnectionFactory'
      - '@router'
    parent: 'PrestaShopBundle\Controller\Admin\FrameworkBundleAdminController'
    public: true
  Sendy\PrestaShop\Controllers\Admin\SettingsController:
    class: 'Sendy\PrestaShop\Controllers\Admin\SettingsController'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
  Sendy\PrestaShop\Controllers\Admin\Orders\CreateShipmentController:
    class: 'Sendy\PrestaShop\Controllers\Admin\Orders\CreateShipmentController'
    arguments:
      - '@Sendy\PrestaShop\Actions\CreateShipmentFromOrder'
  Sendy\PrestaShop\Controllers\Admin\Orders\ColumnsController:
    class: 'Sendy\PrestaShop\Controllers\Admin\Orders\ColumnsController'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'

  Sendy\PrestaShop\Factories\ApiConnectionFactory:
    class: 'Sendy\PrestaShop\Factories\ApiConnectionFactory'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
      - '@router'

  Sendy\PrestaShop\Hooks\ActionOrderGridDefinitionModifier:
    class: 'Sendy\PrestaShop\Hooks\ActionOrderGridDefinitionModifier'
    arguments:
      - '@translator'
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
  Sendy\PrestaShop\Hooks\DisplayAdminOrderSide:
    class: 'Sendy\PrestaShop\Hooks\DisplayAdminOrderSide'
    arguments:
      - '@twig'

  Sendy\PrestaShop\Repositories\AbstractEntityRepository:
    class: 'Sendy\PrestaShop\Repositories\AbstractEntityRepository'
    arguments:
      - '@doctrine.orm.entity_manager'
  Sendy\PrestaShop\Repositories\ShipmentRepository:
    parent: 'Sendy\PrestaShop\Repositories\AbstractEntityRepository'
    public: true
  Sendy\PrestaShop\Repositories\PackageRepository:
    parent: 'Sendy\PrestaShop\Repositories\AbstractEntityRepository'
    public: true
  Sendy\PrestaShop\Repositories\ConfigurationRepository:
    class: 'Sendy\PrestaShop\Repositories\ConfigurationRepository'
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  Sendy\PrestaShop\Settings\AuthenticateForm:
    class: Sendy\PrestaShop\Settings\AuthenticateForm
    arguments:
      - '@translator'
      - "@=service('prestashop.adapter.legacy.context').getLanguages()"
      - '@router'
      - '@Sendy\PrestaShop\Factories\ApiConnectionFactory'
    tags:
      - { name: form.type }
  Sendy\PrestaShop\Settings\SettingsDataManager:
    class: 'Sendy\PrestaShop\Settings\SettingsDataManager'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
  Sendy\PrestaShop\Settings\SettingsForm:
    class: 'Sendy\PrestaShop\Settings\SettingsForm'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }
  sendy.prestashop.settings.settings_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@Sendy\PrestaShop\Settings\SettingsDataManager'
      - 'Sendy\PrestaShop\Settings\SettingsForm'
      - 'Sendy'
