services:
  _defaults:
    public: true

  # Actions
  Sendy\PrestaShop\Actions\ApplyProcessingMethodChange:
    class: 'Sendy\PrestaShop\Actions\ApplyProcessingMethodChange'
    arguments:
      - '@Sendy\PrestaShop\Actions\InstallWebhook'
      - '@Sendy\PrestaShop\Actions\UninstallWebhook'
  Sendy\PrestaShop\Actions\CreateShipmentFromOrder:
    class: 'Sendy\PrestaShop\Actions\CreateShipmentFromOrder'
    arguments:
      - '@Sendy\PrestaShop\Factories\ApiConnectionFactory'
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
  Sendy\PrestaShop\Actions\HandleShipmentWebhook:
    class: 'Sendy\PrestaShop\Actions\HandleShipmentWebhook'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ShipmentRepository'
      - '@Sendy\PrestaShop\Repositories\PackageRepository'
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
      - '@Sendy\PrestaShop\Factories\ApiConnectionFactory'
  Sendy\PrestaShop\Actions\InstallWebhook:
    class: 'Sendy\PrestaShop\Actions\InstallWebhook'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
      - '@router'
      - '@Sendy\PrestaShop\Factories\ApiConnectionFactory'
  Sendy\PrestaShop\Actions\UninstallWebhook:
    class: 'Sendy\PrestaShop\Actions\UninstallWebhook'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
      - '@Sendy\PrestaShop\Factories\ApiConnectionFactory'

  # Controllers
  Sendy\PrestaShop\Controllers\Admin\AuthController:
    class: 'Sendy\PrestaShop\Controllers\Admin\AuthController'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
      - '@Sendy\PrestaShop\Factories\ApiConnectionFactory'
      - '@router'
    parent: 'PrestaShopBundle\Controller\Admin\FrameworkBundleAdminController'
    public: true
  Sendy\PrestaShop\Controllers\Admin\SettingsController:
    class: 'Sendy\PrestaShop\Controllers\Admin\SettingsController'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
      - '@Sendy\PrestaShop\Forms\Settings\SettingsFormHandler'
  Sendy\PrestaShop\Controllers\Admin\Orders\CreateShipmentController:
    class: 'Sendy\PrestaShop\Controllers\Admin\Orders\CreateShipmentController'
    arguments:
      - '@Sendy\PrestaShop\Actions\CreateShipmentFromOrder'
  Sendy\PrestaShop\Controllers\Admin\Orders\PrintLabelController:
    class: 'Sendy\PrestaShop\Controllers\Admin\Orders\PrintLabelController'
    arguments:
      - '@Sendy\PrestaShop\Factories\ApiConnectionFactory'
      - '@Sendy\PrestaShop\Repositories\ShipmentRepository'
  Sendy\PrestaShop\Controllers\Admin\Orders\ColumnsController:
    class: 'Sendy\PrestaShop\Controllers\Admin\Orders\ColumnsController'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
  Sendy\PrestaShop\Controllers\Admin\WebhookController:
    class: 'Sendy\PrestaShop\Controllers\Admin\WebhookController'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ShipmentRepository'
      - '@Sendy\PrestaShop\Actions\HandleShipmentWebhook'

  # Factories
  Sendy\PrestaShop\Factories\ApiConnectionFactory:
    class: 'Sendy\PrestaShop\Factories\ApiConnectionFactory'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
      - '@router'

  # Forms
  Sendy\PrestaShop\Forms\CreateShipment\CreateShipmentForm:
    class: 'Sendy\PrestaShop\Forms\CreateShipment\CreateShipmentForm'
    arguments:
      - '@translator'
      - '@Sendy\PrestaShop\Factories\ApiConnectionFactory'
    tags:
      - { name: form.type }
  Sendy\PrestaShop\Forms\CreateShipment\CreateShipmentFormHandler:
    class: 'Sendy\PrestaShop\Forms\CreateShipment\CreateShipmentFormHandler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@Sendy\PrestaShop\Forms\CreateShipment\CreateShipmentFormDataProvider'
  Sendy\PrestaShop\Forms\CreateShipment\CreateShipmentFormDataProvider:
    class: 'Sendy\PrestaShop\Forms\CreateShipment\CreateShipmentFormDataProvider'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
  Sendy\PrestaShop\Forms\Settings\AuthenticateForm:
    class: Sendy\PrestaShop\Forms\Settings\AuthenticateForm
    arguments:
      - '@translator'
      - "@=service('prestashop.adapter.legacy.context').getLanguages()"
      - '@router'
      - '@Sendy\PrestaShop\Factories\ApiConnectionFactory'
    tags:
      - { name: form.type }
  Sendy\PrestaShop\Forms\Settings\SettingsDataManager:
    class: 'Sendy\PrestaShop\Forms\Settings\SettingsDataManager'
    arguments:
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
  Sendy\PrestaShop\Forms\Settings\SettingsForm:
    class: 'Sendy\PrestaShop\Forms\Settings\SettingsForm'
    arguments:
      - '@translator'
      - '@PrestaShop\PrestaShop\Core\Form\ChoiceProvider\OrderStateByIdChoiceProvider'
    tags:
      - { name: form.type }
  Sendy\PrestaShop\Forms\Settings\SettingsFormHandler:
    class: 'Sendy\PrestaShop\Forms\Settings\SettingsFormHandler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@Sendy\PrestaShop\Forms\Settings\SettingsDataManager'

  # Hooks
  Sendy\PrestaShop\Hooks\ActionAdminControllerSetMedia:
    class: 'Sendy\PrestaShop\Hooks\ActionAdminControllerSetMedia'
    arguments:
      - '@router'
  Sendy\PrestaShop\Hooks\ActionOrderGridDefinitionModifier:
    class: 'Sendy\PrestaShop\Hooks\ActionOrderGridDefinitionModifier'
    arguments:
      - '@translator'
      - '@Sendy\PrestaShop\Repositories\ConfigurationRepository'
  Sendy\PrestaShop\Hooks\DisplayAdminOrderSide:
    class: 'Sendy\PrestaShop\Hooks\DisplayAdminOrderSide'
    arguments:
      - '@twig'
      - '@Sendy\PrestaShop\Forms\CreateShipment\CreateShipmentFormHandler'
      - '@Sendy\PrestaShop\Repositories\ShipmentRepository'
      - '@Sendy\PrestaShop\Repositories\PackageRepository'
  Sendy\PrestaShop\Hooks\DisplayAdminEndContent:
    class: 'Sendy\PrestaShop\Hooks\DisplayAdminEndContent'
    arguments:
      - '@twig'
      - '@Sendy\PrestaShop\Forms\CreateShipment\CreateShipmentFormHandler'

  # Repositories
  Sendy\PrestaShop\Repositories\AbstractEntityRepository:
    class: 'Sendy\PrestaShop\Repositories\AbstractEntityRepository'
    arguments:
      - '@doctrine.orm.entity_manager'
  Sendy\PrestaShop\Repositories\ShipmentRepository:
    parent: 'Sendy\PrestaShop\Repositories\AbstractEntityRepository'
    public: true
  Sendy\PrestaShop\Repositories\PackageRepository:
    parent: 'Sendy\PrestaShop\Repositories\AbstractEntityRepository'
    public: true
  Sendy\PrestaShop\Repositories\ConfigurationRepository:
    class: 'Sendy\PrestaShop\Repositories\ConfigurationRepository'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
